
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: alex_static_pages_homepage
        permanent: true
alex_static_pages:
    resource: "@AlexStaticPagesBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
      _locale: en|es
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /{_locale}
    requirements:
      _locale: en|es
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /{_locale}/admin
    requirements:
      _locale: en|es
