alex_custom_tweet:
    resource: "@AlexCustomTweetBundle/Controller/"
    type:     annotation
    prefix:   /

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: alex_static_pages_homepage
        permanent: true
_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /admin

alex_static_pages:
    resource: "@AlexStaticPagesBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
      _locale: en|es
alex_custom_user:
    resource: "@AlexCustomUserBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
      _locale: en|es
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /{_locale}
    requirements:
      _locale: en|es
EndroidQrCodeBundle:
    resource: "@EndroidQrCodeBundle/Controller/"
    type:     annotation
    prefix:   /qrcode
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /{_locale}/admin
    requirements:
      _locale: en|es
