# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    access_denied_url: fos_user_security_login
    encoders:
      FOS\UserBundle\Model\UserInterface: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
      fos_userbundle:
        id: fos_user.user_provider.username_email
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
          pattern: ^/
          access_denied_handler: app.security.access_denied_handler
          form_login:
            provider: fos_userbundle
            login_path: fos_user_security_login
            csrf_token_generator: security.csrf.token_manager
            check_path: fos_user_security_check
            failure_path: fos_user_security_login
          logout:
            path: fos_user_security_logout
            target: fos_user_security_login
          anonymous:    true
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
      - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/admin, role: ROLE_ADMIN }
      - { path: ^/profile, role: ROLE_USER }
      - { path: ^/admin/, role: ROLE_ADMIN }
      - { path: ^/profile/, role: ROLE_USER }