alex_static_pages_homepage:
    path:     /
    defaults: { _controller: AlexStaticPagesBundle:Default:index }
alex_static_pages_servicios:
    path:     /servicios/
    defaults: { _controller: AlexStaticPagesBundle:Default:servicios }
alex_static_pages_ecomerce:
    path:     /servicios/e-commerce
    defaults: { _controller: AlexStaticPagesBundle:Default:ecom }
alex_static_pages_medida:
    path:     /servicios/amedida
    defaults: { _controller: AlexStaticPagesBundle:Default:medida }
alex_static_pages_integration:
    path:     /servicios/integracion
    defaults: { _controller: AlexStaticPagesBundle:Default:integration }
alex_static_pages_layout:
    path:     /layout
    defaults: { _controller: AlexStaticPagesBundle:Default:layout }
alex_static_pages_contact:
    path:     /contacto
    defaults: { _controller: AlexStaticPagesBundle:Default:contact }
alex_static_pages_about:
    path:     /sobrenosotros
    defaults: { _controller: AlexStaticPagesBundle:Default:sobre }
alex_static_pages_map:
    path:     /map
    defaults: { _controller: AlexStaticPagesBundle:Default:map }
alex_static_pages_contact_post:
    path:     /contacto/post
    defaults: { _controller: AlexStaticPagesBundle:Default:contactpost }
alex_static_pages_contact_succes:
    path:     /contacto/succes
    defaults: { _controller: AlexStaticPagesBundle:Default:formsucces }
alex_static_pages_contact_fail:
    path:     /contacto/fail
    defaults: { _controller: AlexStaticPagesBundle:Default:formfailed }
alex_static_pages_lang_switch:
    path:     /switch
    defaults: { _controller: AlexStaticPagesBundle:Lenguage:switch }
alex_static_pages_lang_eng:
    path:     /english
    defaults: { _controller: AlexStaticPagesBundle:Lenguage:english }
alex_static_pages_lang_cat:
    path:     /catala
    defaults: { _controller: AlexStaticPagesBundle:Lenguage:spanish }
alex_static_pages_lang_es:
    path:     /espanol
    defaults: { _controller: AlexStaticPagesBundle:Lenguage:spanish }
alex_static_pages_qr:
    path:     /qr/{idcon}
    defaults: { _controller: AlexStaticPagesBundle:Default:qr }
alex_static_pages_qr_validation:
    path:     /qrvalidation/{idcon}
    defaults: { _controller: AlexStaticPagesBundle:Default:qrvalidate }
alex_static_pages_tweet_list:
    path:     /tweetlist
    defaults: { _controller: AlexStaticPagesBundle:Default:twitts }
alex_static_pages_sorteos:
    path:     /sorteos
    defaults: { _controller: AlexStaticPagesBundle:Default:sorteos }
alex_static_pages_update_users:
    path:     /update
    defaults: { _controller: AlexStaticPagesBundle:User:asignarteguntwit }
alex_static_pages_users_sorteos:
    path:     /missorteos
    defaults: { _controller: AlexStaticPagesBundle:User:muestratorneos }
