alex_static_pages_homepage:
    path:     /
    defaults: { _controller: AlexStaticPagesBundle:Default:index }
alex_static_pages_ecomerce:
    path:     /servicios/e-commerce
    defaults: { _controller: AlexStaticPagesBundle:Default:ecom }
alex_static_pages_medida:
    path:     /servicios/amedida
    defaults: { _controller: AlexStaticPagesBundle:Default:medida }
alex_static_pages_integration:
    path:     /servicios/integracion
    defaults: { _controller: AlexStaticPagesBundle:Default:integration }
alex_static_pages_layout:
    path:     /layout
    defaults: { _controller: AlexStaticPagesBundle:Default:layout }
alex_static_pages_contact:
    path:     /contacto
    defaults: { _controller: AlexStaticPagesBundle:Default:contact }
alex_static_pages_contact_post:
    path:     /contacto/post
    defaults: { _controller: AlexStaticPagesBundle:Default:contactpost }
alex_static_pages_contact_succes:
    path:     /contacto/succes
    defaults: { _controller: AlexStaticPagesBundle:Default:Default:formsucces }
alex_static_pages_contact_fail:
    path:     /contacto/fail
    defaults: { _controller: AlexStaticPagesBundle:Default:Default:formfailed }
