services:
    app.locale_listener:
        class: Alex\StaticPagesBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }



