services:
    app.locale_listener:
        class: Alex\StaticPagesBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }
    app.sorteo:
      class:  Alex\StaticPagesBundle\Admin\SorteoAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, label: Sorteo }
      arguments: [null, Alex\StaticPagesBundle\Entity\Sorteo, null]

    app.consumicion:
          class:  Alex\StaticPagesBundle\Admin\ConsumicionAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, label: Consumición }
          arguments: [null, Alex\StaticPagesBundle\Entity\Consumicion, null]

    app.admin.user:
              class:  Alex\StaticPagesBundle\Admin\UserAdmin
              tags:
                - { name: sonata.admin, manager_type: orm, label: Usuarios }
              arguments: [null, Alex\StaticPagesBundle\Entity\User, null]

    app.userControler:
      class: Alex\StaticPagesBundle\Controller\UserController



