<?php

namespace Alex\StaticPagesBundle\Repository;

/**
 * ArtefactoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtefactoRepository extends \Doctrine\ORM\EntityRepository
{
}
