<?php

namespace Alex\StaticPagesBundle\Repository;

/**
 * ConsumicionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsumicionRepository extends \Doctrine\ORM\EntityRepository
{
}
