<?php

namespace Alex\StaticPagesBundle\Repository;

/**
 * ValoracionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValoracionRepository extends \Doctrine\ORM\EntityRepository
{
}
